<?php

use Projet\Entite\Chapeau;
use Projet\Entite\Personne;

include_once "Personne.php";

class Employe extends \Projet\Entite\Personne
{
    private string $grade;

    /**
     * @param string $grade
     */
    public function __construct(string $prenom, string $nom, int $age, string $grade)
    {
        $this->prenom = $prenom;
        $this->nom = $nom;
        $this->age = $age;
        $this->grade = $grade;
    }

    /**
     * @return string
     */
    public function getGrade(): string
    {

        return $this->grade;
    }

    /**
     * @param string $grade
     */
    public function setGrade(string $grade): void
    {
        $this->grade = $grade;
    }

    public function __toString(): string
    {
        return parent::__toString() . " $this->grade"; // TODO: Change the autogenerated stub
    }


}

$p = new Employe('tom','quicotte',46, 'formateur');
$p->setChapeau( new Chapeau('rond', 'rose') );
echo $p;